#!/bin/sh -e

passed=0
failed=0


stest() {
    local exp="$1"
    local desc="$2"
    local res=
    shift 2

    echo "----------------------------------------"
    echo "Testing (exp: ${exp}): ${desc}"
    if "$@" </dev/null 1>/dev/null 2>&1; then
        res=pass
    else
        res=fail
    fi

    if [ ${exp} = ${res} ]; then
        echo "Result: OK"
        passed=$((passed+1))
    else
        echo "Result: *** BAD ***"
        echo "Command: $@"
        failed=$((failed+1))
    fi
}


if [ `id -u` != 0  -o  `id -g` != 0 ]; then
    echo "Must be root"
    exit 1
fi

if ! /etc/init.d/tor -q status; then
    echo "Tor daemon must be running"
    exit 1
fi


webhost=torproject.org
webip=38.229.72.16
onionhost=3g2upl4pq6kufc4m.onion


# Check that wireless MAC addresses were changed
for netdev in /sys/class/net/*; do
    if iwconfig "${netdev}" 1>/dev/null 2>&1 && [ -e "${netdev}"/phy80211 ]; then
        wmachw=`cat "${netdev}"/phy80211/macaddress`
        wmac=`cat "${netdev}"/address`
        stest pass "Changed MAC: `basename ${netdev}`" [ ${#wmachw} = ${#wmac} -a "${wmachw}" != "${wmac}" ]
    fi
done


# Clearnet access via HTTP/SOCKS/direct
stest fail "Fetch .org via HTTP proxy as root"                     curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest fail "Fetch .org via HTTP proxy as nofw"     sudo -n -u nofw curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest pass "Fetch .org via HTTP proxy as anon"     sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest pass "Fetch .org via HTTP proxy as cable"    sudo -n -u cable curl -fsSI -x 127.0.0.1:8118               ${webhost}
stest fail "Fetch .org via SOCKS proxy as root"                    curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy as nofw"    sudo -n -u nofw curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy as cable"   sudo -n -u cable curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest pass "Fetch .org via SOCKS proxy as anon"    sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest pass "Fetch .org via SOCKS proxy as privoxy" sudo -n -u privoxy curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as root"                 curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as nofw" sudo -n -u nofw curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as anon" sudo -n -u anon curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as privoxy" sudo -n -u privoxy curl -fsSI --socks5 127.0.0.1:9050 ${webhost}

# Clearnet access w/o proxy
stest fail "Fetch .org w/o proxy as root"                          curl -fsSI -x "" ${webhost}
stest pass "Fetch .org w/o proxy as nofw"          sudo -n -u nofw curl -fsSI -x "" ${webhost}
stest fail "Fetch .org w/o proxy as anon"          sudo -n -u anon curl -fsSI -x "" ${webhost}
stest fail "Fetch .org w/o proxy as tor"           sudo -n -u tor  curl -fsSI -x "" ${webhost}

# Darknet access via HTTP/SOCKS
stest pass "Fetch .onion via HTTP  proxy as anon"  sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${onionhost}
stest pass "Fetch .onion via SOCKS proxy as anon"  sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${onionhost}

# Clearnet IP access via HTTP/SOCKS/direct (SOCKS4=fail <-> SafeSocks=1)
stest pass "Fetch IP via HTTP proxy as anon"       sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${webip}
stest pass "Fetch IP via SOCKS proxy as anon"      sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webip}
stest pass "Fetch IP via SOCKS4 proxy as anon"     sudo -n -u anon curl -fsSI --socks4          127.0.0.1:9050 ${webip}
stest fail "Fetch IP w/o proxy as root"                            curl -fsSI -x ""                            ${webip}
stest fail "Fetch IP w/o proxy as anon"            sudo -n -u anon curl -fsSI -x ""                            ${webip}
stest fail "Fetch IP w/o proxy as privoxy"         sudo -n -u privoxy curl -fsSI -x ""                         ${webip}
stest pass "Fetch IP w/o proxy as tor"             sudo -n -u tor  curl -fsSI -x ""                            ${webip}
stest pass "Fetch IP w/o proxy as nofw"            sudo -n -u nofw curl -fsSI -x ""                            ${webip}


# Tor control port access
stest fail "Access Tor control port as root"                       nc -q 0 127.0.0.1 9051
stest fail "Access Tor control port as anon"       sudo -n -u anon nc -q 0 127.0.0.1 9051
stest pass "Access Tor control port as tor"        sudo -n -u tor  nc -q 0 127.0.0.1 9051
stest pass "Invoke tor-ctrl"                       sudo -n -u tor  tor-ctrl status

# Done
stest pass "Done" :
echo "passed: ${passed}, failed: ${failed}"
